project_name: go-linkchecker
release:
  github:
    owner: skrashevich
    name: go-linkchecker
builds:
  - id: "go-linkchecker"
    main: "./main.go"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
    ldflags: 
      - -s -w
    flags:
      - -trimpath
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  extra_files:
    - glob: '*.md'
snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^examples:'
